# Generated by Django 4.2.2 on 2023-09-15 18:55

from django.db import migrations, models


def backdate_post_balance(apps, schema_editor):
    Transaction = apps.get_model("savings_tracker", "Transaction")
    Account = apps.get_model("savings_tracker", "Account")
    for account in Account.objects.all():
        balance = 0
        for transaction in Transaction.objects.filter(account__id=account.id).order_by('datetime'):
            transaction.post_balance = balance + transaction.amount
            balance = transaction.post_balance
            transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('savings_tracker', '0002_transaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.RunPython(backdate_post_balance),
    ]
