# Generated by Django 4.2.2 on 2023-09-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_tracker', '0003_transaction_post_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
