# Generated by Django 5.0.9 on 2024-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_tracker', '0004_remove_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
