# Generated by Django 5.0.9 on 2026-02-20 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings_tracker", "0005_alter_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtransfer",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="savings_tracker.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="savings_tracker.account",
            ),
        ),
    ]
